# Generated by Django 4.2.6 on 2023-10-26 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, max_length=100)),
                ('service', models.CharField(choices=[('lavado premium basico', 'Lavado Premium Basico'), ('lavado premium plus', 'Lavado Premium Plus'), ('lavado premium deluxe', 'Lavado Premium Deluxe'), ('pulido vehicular', 'Pulido Vehicular'), ('pulido de opticas', 'Pulido de Opticas'), ('polarizado', 'Polarizado'), ('wrapping vehicular', 'Wrapping Vehicular')], default=None, max_length=100, verbose_name='servicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
