# Generated by Django 4.2.6 on 2023-10-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarwash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='time',
            field=models.TimeField(default=None, max_length=100),
        ),
    ]
