# Generated by Django 4.2.6 on 2023-10-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCarwash', '0003_alter_turno_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='service',
            field=models.CharField(choices=[('lavado Premium Basico', 'Lavado Premium Basico'), ('lavado Premium Plus', 'Lavado Premium Plus'), ('lavado Premium Deluxe', 'Lavado Premium Deluxe'), ('pulido Vehicular', 'Pulido Vehicular'), ('pulido de Opticas', 'Pulido de Opticas'), ('polarizado', 'Polarizado'), ('wrapping Vehicular', 'Wrapping Vehicular')], default=None, max_length=100, verbose_name='servicio'),
        ),
    ]
